-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
        },
        rounding = 10,
    },
    general = {
        layout = "scrolling",
    },
    gestures = {
        workspace_swipe_invert = false,
    },
})
